AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WhatsApp Expense Tracker

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024  # Increased from 512MB
    Runtime: python3.11
    Architectures:
      - arm64  # Use ARM64 for better performance/cost
    Environment:
      Variables:
        META_VERIFY_TOKEN: !Ref MetaVerifyToken
        META_APP_SECRET: !Ref MetaAppSecret
        META_ACCESS_TOKEN: !Ref MetaAccessToken
        META_PHONE_NUMBER_ID: !Ref MetaPhoneNumberId

Parameters:
  MetaVerifyToken:
    Type: String
    Description: Meta WhatsApp verify token
  MetaAppSecret:
    Type: String
    Description: Meta WhatsApp app secret
    NoEcho: true
  MetaAccessToken:
    Type: String
    Description: Meta WhatsApp access token
    NoEcho: true
  MetaPhoneNumberId:
    Type: String
    Description: Meta WhatsApp phone number ID
  DatabaseConnection:
    Type: String
    Description: DB connection string
    NoEcho: true
Resources:
  WhatsAppExpenseAPI:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.handler
      Environment:
        Variables:
          DATABASE_URL: !Ref DatabaseConnection
      Events:
        WebhookGet:
          Type: Api
          Properties:
            Path: /webhook/meta
            Method: get
        WebhookPost:
          Type: Api
          Properties:
            Path: /webhook/meta
            Method: post
        Health:
          Type: Api
          Properties:
            Path: /healthz
            Method: get
        Reports:
          Type: Api
          Properties:
            Path: /reports/summary
            Method: get
        Export:
          Type: Api
          Properties:
            Path: /export/csv
            Method: get
        WarmUp:
          Type: Schedule
          Properties:
            Schedule: rate(10 minutes)  # Keep warm every 10 minutes
            Name: WarmUpLambda
            Description: Keep Lambda function warm to reduce cold starts

Outputs:
  WebhookVerifyUrl:
    Description: "WhatsApp webhook verification URL (GET)"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/meta"
  WebhookEventUrl:
    Description: "WhatsApp webhook event URL (POST)"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/meta"
