"""add short_name to categories

Revision ID: c53b5169187d
Revises: 46456f8829c0
Create Date: 2025-09-17 23:44:02.098714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c53b5169187d'
down_revision = '46456f8829c0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('short_name', sa.String(length=48), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('categories', 'short_name')
    # ### end Alembic commands ###
